### PR TITLE
Correcting parameter assignment with appropriate distribution

### PR DESCRIPTION
**Pull request by JoshRack**
Small correction to Section 2 to indicate the alpha parameter was the Exponential distribution and mu was the Uniform distribution

### CODE REVIEW

**Comment by markdregan** [comment]
Thanks Josh. Good catch. However, the model definition in python is correct - but the model definition in MathJax / markup is incorrect. mu should be Uniform(0, 100) and alpha should be Exp(0.2).

**Comment by markdregan** [comment]
@JoshRack - if you can change the markup and revert the python to the original definition - happy to merge this PR.

**Comment by JoshRack** [comment]
@markdregan, I apologize but I must be missing something. I've looked at the differences and this commit was a fix to the markup not the python model. Not sure if you just want to update directly as the line above could also use a tweak as it reads: "Again, we will use a Uniform distribution to estimate both $\mu$ and $\alpha".

**Comment by markdregan** [comment]
My bad Josh - you are correct. Thanks for the PR!

**Pull request merged**
